// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1aZ9_goh6T0htaCAo2GdBS5eKmI9QWJY',
    appId: '1:1060849439887:web:67670eb90cc50855260cfa',
    messagingSenderId: '1060849439887',
    projectId: 'se320-project-cookbook',
    authDomain: 'se320-project-cookbook.firebaseapp.com',
    storageBucket: 'se320-project-cookbook.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjtw7fDZXhVAvyrnFuGjJtrRC2BSQHNo',
    appId: '1:1060849439887:android:e11465ebd2be3cd8260cfa',
    messagingSenderId: '1060849439887',
    projectId: 'se320-project-cookbook',
    storageBucket: 'se320-project-cookbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDufkhZ3jXABkgEtDEYJx4Pj79MfZv3QSg',
    appId: '1:1060849439887:ios:2222293d5ea49f7a260cfa',
    messagingSenderId: '1060849439887',
    projectId: 'se320-project-cookbook',
    storageBucket: 'se320-project-cookbook.appspot.com',
    iosClientId: '1060849439887-ss7b9d9q8k7qll6dhjv82kp4ctedr3nj.apps.googleusercontent.com',
    iosBundleId: 'com.partur.se380Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDufkhZ3jXABkgEtDEYJx4Pj79MfZv3QSg',
    appId: '1:1060849439887:ios:2222293d5ea49f7a260cfa',
    messagingSenderId: '1060849439887',
    projectId: 'se320-project-cookbook',
    storageBucket: 'se320-project-cookbook.appspot.com',
    iosClientId: '1060849439887-ss7b9d9q8k7qll6dhjv82kp4ctedr3nj.apps.googleusercontent.com',
    iosBundleId: 'com.partur.se380Project',
  );
}
